// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npnvkttvxhrzxhicgjrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wbnZrdHR2eGhyenhoaWNnanJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Mjk1NzksImV4cCI6MjA3NDMwNTU3OX0.Z7WAMFAwGUvbdUUd9Sqp_L6OlLWEb6pIZSuVN9Hy1Yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});